version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=agrodb
      - DB_USERNAME=agro_user
      - DB_PASSWORD=agro_pass

  db:
    image: postgres:15
    container_name: pgsql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: agrodb
      POSTGRES_USER: agro_user
      POSTGRES_PASSWORD: agro_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
